import { Button } from "@/components/ui/button";
import { Download, FileText, Loader2 } from "lucide-react";
import React, { useState } from "react";
import { BODY_REGIONS, CRASH_TYPES } from "../data/injuryCorrelation";
import { useGetInsuranceExport } from "../hooks/useQueries";

interface InjuryExportButtonProps {
  reportId: bigint;
}

function getBodyRegionLabel(key: string): string {
  return BODY_REGIONS.find((r) => r.key === key)?.label ?? key;
}

function getCrashTypeLabel(key: string): string {
  return CRASH_TYPES.find((ct) => ct.key === key)?.label ?? key;
}

export default function InjuryExportButton({
  reportId,
}: InjuryExportButtonProps) {
  const [isExporting, setIsExporting] = useState(false);
  const { refetch } = useGetInsuranceExport(reportId);

  const handleExport = async () => {
    setIsExporting(true);
    try {
      const result = await refetch();
      const exportData = result.data;
      if (!exportData) {
        alert("No export data found. Please store the injury record first.");
        return;
      }

      const bodyRegionKeys: string[] = [
        ...new Set(exportData.injuryPhotos.map((p) => p.bodyRegion)),
      ];
      const crashTypeKeys: string[] = [
        ...new Set(exportData.injuryPhotos.map((p) => p.crashType)),
      ];

      const reportDate =
        exportData.injuryPhotos.length > 0
          ? new Date(
              Number(exportData.injuryPhotos[0].timestamp),
            ).toLocaleString("en-GB", {
              day: "2-digit",
              month: "short",
              year: "numeric",
              hour: "2-digit",
              minute: "2-digit",
            })
          : new Date().toLocaleString("en-GB");

      const lines: string[] = [
        "═══════════════════════════════════════════════════════════",
        "         INJURY ANALYSIS REPORT — FOR INSURANCE USE",
        "═══════════════════════════════════════════════════════════",
        "",
        `Report ID:        ${exportData.reportId.toString()}`,
        `Export Date:      ${new Date().toLocaleString("en-GB")}`,
        `Incident Date:    ${reportDate}`,
        "",
        "───────────────────────────────────────────────────────────",
        "INJURY LOCATIONS",
        "───────────────────────────────────────────────────────────",
        ...bodyRegionKeys.map((r) => `  • ${getBodyRegionLabel(r)}`),
        "",
        "───────────────────────────────────────────────────────────",
        "CORRELATED CRASH MECHANISMS",
        "───────────────────────────────────────────────────────────",
        ...crashTypeKeys.map((ct) => `  • ${getCrashTypeLabel(ct)}`),
        "",
        "───────────────────────────────────────────────────────────",
        "ANALYSIS SUMMARY",
        "───────────────────────────────────────────────────────────",
        exportData.summary,
        "",
        "───────────────────────────────────────────────────────────",
        "PHOTO RECORDS",
        "───────────────────────────────────────────────────────────",
        `Total photos stored: ${exportData.injuryPhotos.length}`,
        "",
        ...exportData.injuryPhotos.map((photo, i) =>
          [
            `Photo ${i + 1}:`,
            `  Body Region:  ${getBodyRegionLabel(photo.bodyRegion)}`,
            `  Crash Type:   ${getCrashTypeLabel(photo.crashType)}`,
            `  Recorded:     ${new Date(Number(photo.timestamp)).toLocaleString("en-GB")}`,
            `  Photo ID:     ${photo.id.toString()}`,
            "",
          ].join("\n"),
        ),
        "───────────────────────────────────────────────────────────",
        "IMPORTANT NOTICE",
        "───────────────────────────────────────────────────────────",
        "Please attach the original injury photographs to this report",
        "when submitting to your insurance company.",
        "",
        "This report was generated by the Accident Report System.",
        "═══════════════════════════════════════════════════════════",
      ];

      const content = lines.join("\n");
      const blob = new Blob([content], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `injury-report-${exportData.reportId.toString()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Export failed:", err);
      alert("Export failed. Please try again.");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Button
      onClick={handleExport}
      disabled={isExporting}
      variant="outline"
      className="w-full gap-2"
    >
      {isExporting ? (
        <>
          <Loader2 className="h-4 w-4 animate-spin" />
          Generating Export…
        </>
      ) : (
        <>
          <FileText className="h-4 w-4" />
          <Download className="h-4 w-4" />
          Export for Insurance
        </>
      )}
    </Button>
  );
}
