/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoadType = IDL.Variant({
  'urban' : IDL.Nat,
  'dualCarriageway' : IDL.Nat,
  'motorway' : IDL.Nat,
});
export const PhotoMetadata = IDL.Record({
  'contentType' : IDL.Text,
  'description' : IDL.Text,
  'uploadTimestamp' : IDL.Int,
  'filename' : IDL.Text,
});
export const TrafficSignalState = IDL.Record({
  'color' : IDL.Text,
  'proximityToAccident' : IDL.Nat,
  'witnessTestimony' : IDL.Text,
  'position' : IDL.Text,
});
export const TrafficSign = IDL.Record({
  'detectedInPhoto' : IDL.Bool,
  'signType' : IDL.Text,
  'timestamp' : IDL.Int,
  'position' : IDL.Opt(IDL.Text),
});
export const Surroundings = IDL.Record({
  'roadCondition' : IDL.Text,
  'visibility' : IDL.Text,
  'weather' : IDL.Text,
});
export const VehicleInfo = IDL.Record({
  'mot' : IDL.Text,
  'model' : IDL.Text,
  'registration' : IDL.Text,
  'make' : IDL.Text,
  'year' : IDL.Nat,
  'licencePlate' : IDL.Text,
  'colour' : IDL.Text,
});
export const OtherVehicle = IDL.Record({
  'mot' : IDL.Text,
  'model' : IDL.Text,
  'ownerName' : IDL.Text,
  'registration' : IDL.Text,
  'make' : IDL.Text,
  'year' : IDL.Nat,
  'insurancePolicyNumber' : IDL.Text,
  'claimReference' : IDL.Text,
  'email' : IDL.Text,
  'insurer' : IDL.Text,
  'licencePlate' : IDL.Text,
  'phone' : IDL.Text,
  'colour' : IDL.Text,
});
export const Witness = IDL.Record({
  'statement' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const EvidenceGap = IDL.Record({
  'description' : IDL.Text,
  'confidenceLevel' : IDL.Nat,
  'evidenceType' : IDL.Text,
});
export const AccidentNarrative = IDL.Record({
  'narrativeText' : IDL.Text,
  'evidenceGaps' : IDL.Vec(EvidenceGap),
});
export const VehicleZoneHeatMap = IDL.Record({
  'color' : IDL.Text,
  'zone' : IDL.Text,
  'severity' : IDL.Nat,
});
export const VehicleZoneScore = IDL.Record({
  'zone' : IDL.Text,
  'description' : IDL.Text,
  'score' : IDL.Nat,
  'damageType' : IDL.Text,
});
export const DamageSeverity = IDL.Record({
  'totalLossProbability' : IDL.Nat,
  'severityLabel' : IDL.Text,
  'heatMap' : IDL.Vec(VehicleZoneHeatMap),
  'priorityScore' : IDL.Nat,
  'vehicleZones' : IDL.Vec(VehicleZoneScore),
});
export const FaultLikelihoodAssessment = IDL.Record({
  'partyBPercentage' : IDL.Nat,
  'supportingFactors' : IDL.Vec(IDL.Text),
  'conflictingFactors' : IDL.Vec(IDL.Text),
  'reasoning' : IDL.Text,
  'confidenceLevel' : IDL.Nat,
  'partyAPercentage' : IDL.Nat,
  'roadPositionImpact' : IDL.Text,
});
export const AIAnalysisResult = IDL.Record({
  'dashCamAnalysis' : IDL.Text,
  'inferredCrashType' : IDL.Text,
  'narrativeText' : IDL.Text,
  'photoAnalysis' : IDL.Text,
  'correlationSummary' : IDL.Text,
  'severity' : IDL.Text,
  'evidenceGaps' : IDL.Vec(EvidenceGap),
});
export const DashCamAnalysis = IDL.Record({
  'collisionDetected' : IDL.Bool,
  'timestamps' : IDL.Vec(IDL.Int),
  'faultIndicators' : IDL.Text,
  'roadConditions' : IDL.Text,
  'vehicleSpeed' : IDL.Nat,
});
export const Violation = IDL.Record({
  'detectedAt' : IDL.Int,
  'description' : IDL.Text,
  'violationType' : IDL.Text,
});
export const HighwayCodeRule = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'ruleNumber' : IDL.Text,
  'applicableScenarios' : IDL.Vec(IDL.Text),
});
export const FaultAnalysis = IDL.Record({
  'weatherConditions' : IDL.Opt(IDL.Text),
  'speedLimit' : IDL.Opt(IDL.Nat),
  'isAtFault' : IDL.Bool,
  'violatedRules' : IDL.Vec(HighwayCodeRule),
  'actualSpeed' : IDL.Opt(IDL.Nat),
  'reason' : IDL.Text,
});
export const AccidentReport = IDL.Record({
  'party2Liability' : IDL.Opt(IDL.Nat),
  'vehicleInfo' : VehicleInfo,
  'faultLikelihoodAssessment' : IDL.Opt(FaultLikelihoodAssessment),
  'dashCamAnalysis' : IDL.Opt(DashCamAnalysis),
  'isRedLightViolation' : IDL.Bool,
  'damageDescription' : IDL.Text,
  'imageData' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  'trafficSignalState' : IDL.Opt(TrafficSignalState),
  'otherVehicle' : IDL.Opt(OtherVehicle),
  'owner' : IDL.Opt(IDL.Principal),
  'party1Liability' : IDL.Opt(IDL.Nat),
  'aiAnalysisResult' : IDL.Opt(AIAnalysisResult),
  'stopLocation' : IDL.Text,
  'violations' : IDL.Vec(Violation),
  'applicableRules' : IDL.Vec(HighwayCodeRule),
  'damageSeverity' : IDL.Opt(DamageSeverity),
  'trafficSigns' : IDL.Vec(TrafficSign),
  'faultReasoning' : IDL.Text,
  'surroundings' : Surroundings,
  'timestamp' : IDL.Int,
  'isAtFault' : IDL.Bool,
  'accidentMarker' : IDL.Text,
  'witnesses' : IDL.Vec(Witness),
  'videos' : IDL.Vec(ExternalBlob),
  'vehicleSpeed' : IDL.Nat,
  'dashCamFootage' : IDL.Vec(ExternalBlob),
  'photos' : IDL.Vec(PhotoMetadata),
  'witnessStatement' : IDL.Text,
  'faultAnalysis' : IDL.Opt(FaultAnalysis),
  'accidentNarrative' : IDL.Opt(AccidentNarrative),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const InjuryPhoto = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'bodyRegion' : IDL.Text,
  'timestamp' : IDL.Int,
  'reportId' : IDL.Nat,
  'crashType' : IDL.Text,
});
export const InsuranceExport = IDL.Record({
  'owner' : IDL.Principal,
  'summary' : IDL.Text,
  'injuryPhotos' : IDL.Vec(InjuryPhoto),
  'reportId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addInjuryPhotos' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(ExternalBlob, IDL.Text, IDL.Text))],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReport' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        RoadType,
        IDL.Vec(PhotoMetadata),
        IDL.Vec(IDL.Vec(IDL.Nat8)),
        IDL.Opt(TrafficSignalState),
        IDL.Vec(TrafficSign),
        IDL.Text,
        Surroundings,
        VehicleInfo,
        IDL.Opt(OtherVehicle),
        IDL.Vec(Witness),
        IDL.Vec(ExternalBlob),
        IDL.Vec(ExternalBlob),
        IDL.Opt(AccidentNarrative),
        IDL.Opt(DamageSeverity),
        IDL.Opt(FaultLikelihoodAssessment),
        IDL.Text,
        IDL.Text,
        IDL.Vec(EvidenceGap),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteInjuryPhotos' : IDL.Func([IDL.Nat], [], []),
  'getAIAnalysisResult' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(AIAnalysisResult)],
      ['query'],
    ),
  'getAllPhotos' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(PhotoMetadata))],
      ['query'],
    ),
  'getAllReports' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, AccidentReport))],
      ['query'],
    ),
  'getAllThumbnails' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(PhotoMetadata)))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComprehensiveAssessment' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'faultLikelihoodAssessment' : IDL.Opt(FaultLikelihoodAssessment),
          'damageSeverity' : IDL.Opt(DamageSeverity),
          'accidentNarrative' : IDL.Opt(AccidentNarrative),
        }),
      ],
      ['query'],
    ),
  'getDashCamAnalysis' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(DashCamAnalysis)],
      ['query'],
    ),
  'getEvidenceGaps' : IDL.Func([IDL.Nat], [IDL.Vec(EvidenceGap)], ['query']),
  'getFirstPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(PhotoMetadata)], ['query']),
  'getInjuryPhotos' : IDL.Func([IDL.Nat], [IDL.Vec(InjuryPhoto)], ['query']),
  'getInsuranceExport' : IDL.Func([IDL.Nat], [InsuranceExport], ['query']),
  'getPersistentDashCamAnalysis' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getPersistentPhotoAnalysis' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(AccidentReport)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'storeInjuryPhotos' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateAccidentAssessment' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(AccidentNarrative),
        IDL.Opt(DamageSeverity),
        IDL.Opt(FaultLikelihoodAssessment),
      ],
      [],
      [],
    ),
  'updateDashCamFootage' : IDL.Func([IDL.Nat, IDL.Vec(ExternalBlob)], [], []),
  'updateDashCamFootageImaging' : IDL.Func(
      [IDL.Nat, IDL.Vec(ExternalBlob)],
      [],
      [],
    ),
  'updateEIPhotoAnalysis' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateNewAIResults' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(EvidenceGap)],
      [],
      [],
    ),
  'uploadPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [PhotoMetadata], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoadType = IDL.Variant({
    'urban' : IDL.Nat,
    'dualCarriageway' : IDL.Nat,
    'motorway' : IDL.Nat,
  });
  const PhotoMetadata = IDL.Record({
    'contentType' : IDL.Text,
    'description' : IDL.Text,
    'uploadTimestamp' : IDL.Int,
    'filename' : IDL.Text,
  });
  const TrafficSignalState = IDL.Record({
    'color' : IDL.Text,
    'proximityToAccident' : IDL.Nat,
    'witnessTestimony' : IDL.Text,
    'position' : IDL.Text,
  });
  const TrafficSign = IDL.Record({
    'detectedInPhoto' : IDL.Bool,
    'signType' : IDL.Text,
    'timestamp' : IDL.Int,
    'position' : IDL.Opt(IDL.Text),
  });
  const Surroundings = IDL.Record({
    'roadCondition' : IDL.Text,
    'visibility' : IDL.Text,
    'weather' : IDL.Text,
  });
  const VehicleInfo = IDL.Record({
    'mot' : IDL.Text,
    'model' : IDL.Text,
    'registration' : IDL.Text,
    'make' : IDL.Text,
    'year' : IDL.Nat,
    'licencePlate' : IDL.Text,
    'colour' : IDL.Text,
  });
  const OtherVehicle = IDL.Record({
    'mot' : IDL.Text,
    'model' : IDL.Text,
    'ownerName' : IDL.Text,
    'registration' : IDL.Text,
    'make' : IDL.Text,
    'year' : IDL.Nat,
    'insurancePolicyNumber' : IDL.Text,
    'claimReference' : IDL.Text,
    'email' : IDL.Text,
    'insurer' : IDL.Text,
    'licencePlate' : IDL.Text,
    'phone' : IDL.Text,
    'colour' : IDL.Text,
  });
  const Witness = IDL.Record({
    'statement' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const EvidenceGap = IDL.Record({
    'description' : IDL.Text,
    'confidenceLevel' : IDL.Nat,
    'evidenceType' : IDL.Text,
  });
  const AccidentNarrative = IDL.Record({
    'narrativeText' : IDL.Text,
    'evidenceGaps' : IDL.Vec(EvidenceGap),
  });
  const VehicleZoneHeatMap = IDL.Record({
    'color' : IDL.Text,
    'zone' : IDL.Text,
    'severity' : IDL.Nat,
  });
  const VehicleZoneScore = IDL.Record({
    'zone' : IDL.Text,
    'description' : IDL.Text,
    'score' : IDL.Nat,
    'damageType' : IDL.Text,
  });
  const DamageSeverity = IDL.Record({
    'totalLossProbability' : IDL.Nat,
    'severityLabel' : IDL.Text,
    'heatMap' : IDL.Vec(VehicleZoneHeatMap),
    'priorityScore' : IDL.Nat,
    'vehicleZones' : IDL.Vec(VehicleZoneScore),
  });
  const FaultLikelihoodAssessment = IDL.Record({
    'partyBPercentage' : IDL.Nat,
    'supportingFactors' : IDL.Vec(IDL.Text),
    'conflictingFactors' : IDL.Vec(IDL.Text),
    'reasoning' : IDL.Text,
    'confidenceLevel' : IDL.Nat,
    'partyAPercentage' : IDL.Nat,
    'roadPositionImpact' : IDL.Text,
  });
  const AIAnalysisResult = IDL.Record({
    'dashCamAnalysis' : IDL.Text,
    'inferredCrashType' : IDL.Text,
    'narrativeText' : IDL.Text,
    'photoAnalysis' : IDL.Text,
    'correlationSummary' : IDL.Text,
    'severity' : IDL.Text,
    'evidenceGaps' : IDL.Vec(EvidenceGap),
  });
  const DashCamAnalysis = IDL.Record({
    'collisionDetected' : IDL.Bool,
    'timestamps' : IDL.Vec(IDL.Int),
    'faultIndicators' : IDL.Text,
    'roadConditions' : IDL.Text,
    'vehicleSpeed' : IDL.Nat,
  });
  const Violation = IDL.Record({
    'detectedAt' : IDL.Int,
    'description' : IDL.Text,
    'violationType' : IDL.Text,
  });
  const HighwayCodeRule = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'ruleNumber' : IDL.Text,
    'applicableScenarios' : IDL.Vec(IDL.Text),
  });
  const FaultAnalysis = IDL.Record({
    'weatherConditions' : IDL.Opt(IDL.Text),
    'speedLimit' : IDL.Opt(IDL.Nat),
    'isAtFault' : IDL.Bool,
    'violatedRules' : IDL.Vec(HighwayCodeRule),
    'actualSpeed' : IDL.Opt(IDL.Nat),
    'reason' : IDL.Text,
  });
  const AccidentReport = IDL.Record({
    'party2Liability' : IDL.Opt(IDL.Nat),
    'vehicleInfo' : VehicleInfo,
    'faultLikelihoodAssessment' : IDL.Opt(FaultLikelihoodAssessment),
    'dashCamAnalysis' : IDL.Opt(DashCamAnalysis),
    'isRedLightViolation' : IDL.Bool,
    'damageDescription' : IDL.Text,
    'imageData' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'trafficSignalState' : IDL.Opt(TrafficSignalState),
    'otherVehicle' : IDL.Opt(OtherVehicle),
    'owner' : IDL.Opt(IDL.Principal),
    'party1Liability' : IDL.Opt(IDL.Nat),
    'aiAnalysisResult' : IDL.Opt(AIAnalysisResult),
    'stopLocation' : IDL.Text,
    'violations' : IDL.Vec(Violation),
    'applicableRules' : IDL.Vec(HighwayCodeRule),
    'damageSeverity' : IDL.Opt(DamageSeverity),
    'trafficSigns' : IDL.Vec(TrafficSign),
    'faultReasoning' : IDL.Text,
    'surroundings' : Surroundings,
    'timestamp' : IDL.Int,
    'isAtFault' : IDL.Bool,
    'accidentMarker' : IDL.Text,
    'witnesses' : IDL.Vec(Witness),
    'videos' : IDL.Vec(ExternalBlob),
    'vehicleSpeed' : IDL.Nat,
    'dashCamFootage' : IDL.Vec(ExternalBlob),
    'photos' : IDL.Vec(PhotoMetadata),
    'witnessStatement' : IDL.Text,
    'faultAnalysis' : IDL.Opt(FaultAnalysis),
    'accidentNarrative' : IDL.Opt(AccidentNarrative),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const InjuryPhoto = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'bodyRegion' : IDL.Text,
    'timestamp' : IDL.Int,
    'reportId' : IDL.Nat,
    'crashType' : IDL.Text,
  });
  const InsuranceExport = IDL.Record({
    'owner' : IDL.Principal,
    'summary' : IDL.Text,
    'injuryPhotos' : IDL.Vec(InjuryPhoto),
    'reportId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addInjuryPhotos' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(ExternalBlob, IDL.Text, IDL.Text))],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReport' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          RoadType,
          IDL.Vec(PhotoMetadata),
          IDL.Vec(IDL.Vec(IDL.Nat8)),
          IDL.Opt(TrafficSignalState),
          IDL.Vec(TrafficSign),
          IDL.Text,
          Surroundings,
          VehicleInfo,
          IDL.Opt(OtherVehicle),
          IDL.Vec(Witness),
          IDL.Vec(ExternalBlob),
          IDL.Vec(ExternalBlob),
          IDL.Opt(AccidentNarrative),
          IDL.Opt(DamageSeverity),
          IDL.Opt(FaultLikelihoodAssessment),
          IDL.Text,
          IDL.Text,
          IDL.Vec(EvidenceGap),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteInjuryPhotos' : IDL.Func([IDL.Nat], [], []),
    'getAIAnalysisResult' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AIAnalysisResult)],
        ['query'],
      ),
    'getAllPhotos' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(PhotoMetadata))],
        ['query'],
      ),
    'getAllReports' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, AccidentReport))],
        ['query'],
      ),
    'getAllThumbnails' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(PhotoMetadata)))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComprehensiveAssessment' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'faultLikelihoodAssessment' : IDL.Opt(FaultLikelihoodAssessment),
            'damageSeverity' : IDL.Opt(DamageSeverity),
            'accidentNarrative' : IDL.Opt(AccidentNarrative),
          }),
        ],
        ['query'],
      ),
    'getDashCamAnalysis' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(DashCamAnalysis)],
        ['query'],
      ),
    'getEvidenceGaps' : IDL.Func([IDL.Nat], [IDL.Vec(EvidenceGap)], ['query']),
    'getFirstPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(PhotoMetadata)], ['query']),
    'getInjuryPhotos' : IDL.Func([IDL.Nat], [IDL.Vec(InjuryPhoto)], ['query']),
    'getInsuranceExport' : IDL.Func([IDL.Nat], [InsuranceExport], ['query']),
    'getPersistentDashCamAnalysis' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getPersistentPhotoAnalysis' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(AccidentReport)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'storeInjuryPhotos' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateAccidentAssessment' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(AccidentNarrative),
          IDL.Opt(DamageSeverity),
          IDL.Opt(FaultLikelihoodAssessment),
        ],
        [],
        [],
      ),
    'updateDashCamFootage' : IDL.Func([IDL.Nat, IDL.Vec(ExternalBlob)], [], []),
    'updateDashCamFootageImaging' : IDL.Func(
        [IDL.Nat, IDL.Vec(ExternalBlob)],
        [],
        [],
      ),
    'updateEIPhotoAnalysis' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateNewAIResults' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(EvidenceGap)],
        [],
        [],
      ),
    'uploadPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [PhotoMetadata],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };