/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccidentReport {
  'party2Liability' : [] | [bigint],
  'isRedLightViolation' : boolean,
  'damageDescription' : string,
  'roadCondition' : string,
  'imageData' : Array<Uint8Array>,
  'trafficSignalState' : [] | [TrafficSignalState],
  'owner' : [] | [Principal],
  'party1Liability' : [] | [bigint],
  'stopLocation' : string,
  'violations' : Array<Violation>,
  'applicableRules' : Array<HighwayCodeRule>,
  'trafficSigns' : Array<TrafficSign>,
  'faultReasoning' : string,
  'timestamp' : bigint,
  'isAtFault' : boolean,
  'accidentMarker' : string,
  'vehicleSpeed' : bigint,
  'photos' : Array<PhotoMetadata>,
  'witnessStatement' : string,
  'faultAnalysis' : [] | [FaultAnalysis],
}
export interface FaultAnalysis {
  'weatherConditions' : [] | [string],
  'speedLimit' : [] | [bigint],
  'isAtFault' : boolean,
  'violatedRules' : Array<HighwayCodeRule>,
  'actualSpeed' : [] | [bigint],
  'reason' : string,
}
export interface HighwayCodeRule {
  'title' : string,
  'description' : string,
  'ruleNumber' : string,
  'applicableScenarios' : Array<string>,
}
export interface PhotoMetadata {
  'contentType' : string,
  'description' : string,
  'uploadTimestamp' : bigint,
  'filename' : string,
}
export type RoadType = { 'urban' : bigint } |
  { 'dualCarriageway' : bigint } |
  { 'motorway' : bigint };
export interface TrafficSign {
  'detectedInPhoto' : boolean,
  'signType' : string,
  'timestamp' : bigint,
  'position' : [] | [string],
}
export interface TrafficSignalState {
  'color' : string,
  'proximityToAccident' : bigint,
  'witnessTestimony' : string,
  'position' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'licenseNumber' : string,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Violation {
  'detectedAt' : bigint,
  'description' : string,
  'violationType' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReport' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      bigint,
      RoadType,
      Array<PhotoMetadata>,
      Array<Uint8Array>,
      [] | [TrafficSignalState],
      Array<TrafficSign>,
      string,
    ],
    bigint
  >,
  'getAllPhotos' : ActorMethod<[bigint], [] | [Array<PhotoMetadata>]>,
  'getAllReports' : ActorMethod<[], Array<[bigint, AccidentReport]>>,
  'getAllThumbnails' : ActorMethod<[], Array<[bigint, Array<PhotoMetadata>]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFirstPhoto' : ActorMethod<[bigint], [] | [PhotoMetadata]>,
  'getReport' : ActorMethod<[bigint], [] | [AccidentReport]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadPhoto' : ActorMethod<[string, string, string], PhotoMetadata>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];