/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HighwayCodeRule {
    title: string;
    description: string;
    ruleNumber: string;
    applicableScenarios: Array<string>;
}
export interface FaultAnalysis {
    weatherConditions?: string;
    speedLimit?: bigint;
    isAtFault: boolean;
    violatedRules: Array<HighwayCodeRule>;
    actualSpeed?: bigint;
    reason: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TrafficSignalState {
    color: string;
    proximityToAccident: bigint;
    witnessTestimony: string;
    position: string;
}
export interface PhotoMetadata {
    contentType: string;
    description: string;
    uploadTimestamp: bigint;
    filename: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Violation {
    detectedAt: bigint;
    description: string;
    violationType: string;
}
export interface InsuranceExport {
    owner: Principal;
    summary: string;
    injuryPhotos: Array<InjuryPhoto>;
    reportId: bigint;
}
export interface AccidentReport {
    party2Liability?: bigint;
    vehicleInfo: VehicleInfo;
    isRedLightViolation: boolean;
    damageDescription: string;
    imageData: Array<Uint8Array>;
    trafficSignalState?: TrafficSignalState;
    otherVehicle?: OtherVehicle;
    owner?: Principal;
    party1Liability?: bigint;
    aiAnalysisResult?: AIAnalysisResult;
    stopLocation: string;
    violations: Array<Violation>;
    applicableRules: Array<HighwayCodeRule>;
    trafficSigns: Array<TrafficSign>;
    faultReasoning: string;
    surroundings: Surroundings;
    timestamp: bigint;
    isAtFault: boolean;
    accidentMarker: string;
    witnesses: Array<Witness>;
    videos: Array<ExternalBlob>;
    vehicleSpeed: bigint;
    photos: Array<PhotoMetadata>;
    witnessStatement: string;
    faultAnalysis?: FaultAnalysis;
}
export type RoadType = {
    __kind__: "urban";
    urban: bigint;
} | {
    __kind__: "dualCarriageway";
    dualCarriageway: bigint;
} | {
    __kind__: "motorway";
    motorway: bigint;
};
export interface AIAnalysisResult {
    inferredCrashType: string;
    narrativeText: string;
    correlationSummary: string;
    severity: string;
}
export interface VehicleInfo {
    mot: string;
    model: string;
    registration: string;
    make: string;
    year: bigint;
    licencePlate: string;
    colour: string;
}
export interface Surroundings {
    roadCondition: string;
    visibility: string;
    weather: string;
}
export interface TrafficSign {
    detectedInPhoto: boolean;
    signType: string;
    timestamp: bigint;
    position?: string;
}
export interface InjuryPhoto {
    id: bigint;
    blob: ExternalBlob;
    bodyRegion: string;
    timestamp: bigint;
    reportId: bigint;
    crashType: string;
}
export interface OtherVehicle {
    mot: string;
    model: string;
    ownerName: string;
    registration: string;
    make: string;
    year: bigint;
    insurancePolicyNumber: string;
    claimReference: string;
    email: string;
    insurer: string;
    licencePlate: string;
    phone: string;
    colour: string;
}
export interface Witness {
    statement: string;
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
    licenseNumber: string;
    phoneNumber: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addInjuryPhotos(reportId: bigint, photoBlobs: Array<[ExternalBlob, string, string]>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createReport(vehicleSpeed: bigint, witnessStatement: string, damageDescription: string, stopLocation: string, accidentMarker: string, timestamp: bigint, roadType: RoadType, photos: Array<PhotoMetadata>, images: Array<Uint8Array>, trafficSignalState: TrafficSignalState | null, trafficSigns: Array<TrafficSign>, gpsLocation: string, surroundings: Surroundings, vehicleInfo: VehicleInfo, otherVehicle: OtherVehicle | null, witnessDetails: Array<Witness>, videoFiles: Array<ExternalBlob>): Promise<bigint>;
    deleteInjuryPhotos(reportId: bigint): Promise<void>;
    getAIAnalysisResult(reportId: bigint): Promise<AIAnalysisResult | null>;
    getAllPhotos(reportId: bigint): Promise<Array<PhotoMetadata> | null>;
    getAllReports(): Promise<Array<[bigint, AccidentReport]>>;
    getAllThumbnails(): Promise<Array<[bigint, Array<PhotoMetadata>]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFirstPhoto(reportId: bigint): Promise<PhotoMetadata | null>;
    getInjuryPhotos(reportId: bigint): Promise<Array<InjuryPhoto>>;
    getInsuranceExport(reportId: bigint): Promise<InsuranceExport>;
    getReport(reportId: bigint): Promise<AccidentReport | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    storeAIAnalysisResult(reportId: bigint, analysisResult: AIAnalysisResult): Promise<void>;
    storeInjuryPhotos(reportId: bigint, summary: string): Promise<void>;
    uploadPhoto(filename: string, contentType: string, description: string): Promise<PhotoMetadata>;
}
import type { AIAnalysisResult as _AIAnalysisResult, AccidentReport as _AccidentReport, ExternalBlob as _ExternalBlob, FaultAnalysis as _FaultAnalysis, HighwayCodeRule as _HighwayCodeRule, InjuryPhoto as _InjuryPhoto, InsuranceExport as _InsuranceExport, OtherVehicle as _OtherVehicle, PhotoMetadata as _PhotoMetadata, RoadType as _RoadType, Surroundings as _Surroundings, TrafficSign as _TrafficSign, TrafficSignalState as _TrafficSignalState, UserProfile as _UserProfile, UserRole as _UserRole, VehicleInfo as _VehicleInfo, Violation as _Violation, Witness as _Witness, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addInjuryPhotos(arg0: bigint, arg1: Array<[ExternalBlob, string, string]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInjuryPhotos(arg0, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInjuryPhotos(arg0, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createReport(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: RoadType, arg7: Array<PhotoMetadata>, arg8: Array<Uint8Array>, arg9: TrafficSignalState | null, arg10: Array<TrafficSign>, arg11: string, arg12: Surroundings, arg13: VehicleInfo, arg14: OtherVehicle | null, arg15: Array<Witness>, arg16: Array<ExternalBlob>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_RoadType_n13(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg9), to_candid_vec_n16(this._uploadFile, this._downloadFile, arg10), arg11, arg12, arg13, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg14), arg15, await to_candid_vec_n20(this._uploadFile, this._downloadFile, arg16));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_RoadType_n13(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg9), to_candid_vec_n16(this._uploadFile, this._downloadFile, arg10), arg11, arg12, arg13, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg14), arg15, await to_candid_vec_n20(this._uploadFile, this._downloadFile, arg16));
            return result;
        }
    }
    async deleteInjuryPhotos(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInjuryPhotos(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInjuryPhotos(arg0);
            return result;
        }
    }
    async getAIAnalysisResult(arg0: bigint): Promise<AIAnalysisResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIAnalysisResult(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIAnalysisResult(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPhotos(arg0: bigint): Promise<Array<PhotoMetadata> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPhotos(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPhotos(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReports(): Promise<Array<[bigint, AccidentReport]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReports();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReports();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllThumbnails(): Promise<Array<[bigint, Array<PhotoMetadata>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllThumbnails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllThumbnails();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFirstPhoto(arg0: bigint): Promise<PhotoMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFirstPhoto(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFirstPhoto(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInjuryPhotos(arg0: bigint): Promise<Array<InjuryPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInjuryPhotos(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInjuryPhotos(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInsuranceExport(arg0: bigint): Promise<InsuranceExport> {
        if (this.processError) {
            try {
                const result = await this.actor.getInsuranceExport(arg0);
                return from_candid_InsuranceExport_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInsuranceExport(arg0);
            return from_candid_InsuranceExport_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: bigint): Promise<AccidentReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async storeAIAnalysisResult(arg0: bigint, arg1: AIAnalysisResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeAIAnalysisResult(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeAIAnalysisResult(arg0, arg1);
            return result;
        }
    }
    async storeInjuryPhotos(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeInjuryPhotos(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeInjuryPhotos(arg0, arg1);
            return result;
        }
    }
    async uploadPhoto(arg0: string, arg1: string, arg2: string): Promise<PhotoMetadata> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhoto(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhoto(arg0, arg1, arg2);
            return result;
        }
    }
}
async function from_candid_AccidentReport_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccidentReport): Promise<AccidentReport> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FaultAnalysis_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FaultAnalysis): FaultAnalysis {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_InjuryPhoto_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InjuryPhoto): Promise<InjuryPhoto> {
    return await from_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_InsuranceExport_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsuranceExport): Promise<InsuranceExport> {
    return await from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_TrafficSign_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrafficSign): TrafficSign {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AIAnalysisResult]): AIAnalysisResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_PhotoMetadata>]): Array<PhotoMetadata> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrafficSignalState]): TrafficSignalState | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OtherVehicle]): OtherVehicle | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FaultAnalysis]): FaultAnalysis | null {
    return value.length === 0 ? null : from_candid_FaultAnalysis_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PhotoMetadata]): PhotoMetadata | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AccidentReport]): Promise<AccidentReport | null> {
    return value.length === 0 ? null : await from_candid_AccidentReport_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    party2Liability: [] | [bigint];
    vehicleInfo: _VehicleInfo;
    isRedLightViolation: boolean;
    damageDescription: string;
    imageData: Array<Uint8Array>;
    trafficSignalState: [] | [_TrafficSignalState];
    otherVehicle: [] | [_OtherVehicle];
    owner: [] | [Principal];
    party1Liability: [] | [bigint];
    aiAnalysisResult: [] | [_AIAnalysisResult];
    stopLocation: string;
    violations: Array<_Violation>;
    applicableRules: Array<_HighwayCodeRule>;
    trafficSigns: Array<_TrafficSign>;
    faultReasoning: string;
    surroundings: _Surroundings;
    timestamp: bigint;
    isAtFault: boolean;
    accidentMarker: string;
    witnesses: Array<_Witness>;
    videos: Array<_ExternalBlob>;
    vehicleSpeed: bigint;
    photos: Array<_PhotoMetadata>;
    witnessStatement: string;
    faultAnalysis: [] | [_FaultAnalysis];
}): Promise<{
    party2Liability?: bigint;
    vehicleInfo: VehicleInfo;
    isRedLightViolation: boolean;
    damageDescription: string;
    imageData: Array<Uint8Array>;
    trafficSignalState?: TrafficSignalState;
    otherVehicle?: OtherVehicle;
    owner?: Principal;
    party1Liability?: bigint;
    aiAnalysisResult?: AIAnalysisResult;
    stopLocation: string;
    violations: Array<Violation>;
    applicableRules: Array<HighwayCodeRule>;
    trafficSigns: Array<TrafficSign>;
    faultReasoning: string;
    surroundings: Surroundings;
    timestamp: bigint;
    isAtFault: boolean;
    accidentMarker: string;
    witnesses: Array<Witness>;
    videos: Array<ExternalBlob>;
    vehicleSpeed: bigint;
    photos: Array<PhotoMetadata>;
    witnessStatement: string;
    faultAnalysis?: FaultAnalysis;
}> {
    return {
        party2Liability: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.party2Liability)),
        vehicleInfo: value.vehicleInfo,
        isRedLightViolation: value.isRedLightViolation,
        damageDescription: value.damageDescription,
        imageData: value.imageData,
        trafficSignalState: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.trafficSignalState)),
        otherVehicle: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.otherVehicle)),
        owner: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.owner)),
        party1Liability: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.party1Liability)),
        aiAnalysisResult: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.aiAnalysisResult)),
        stopLocation: value.stopLocation,
        violations: value.violations,
        applicableRules: value.applicableRules,
        trafficSigns: from_candid_vec_n30(_uploadFile, _downloadFile, value.trafficSigns),
        faultReasoning: value.faultReasoning,
        surroundings: value.surroundings,
        timestamp: value.timestamp,
        isAtFault: value.isAtFault,
        accidentMarker: value.accidentMarker,
        witnesses: value.witnesses,
        videos: await from_candid_vec_n34(_uploadFile, _downloadFile, value.videos),
        vehicleSpeed: value.vehicleSpeed,
        photos: value.photos,
        witnessStatement: value.witnessStatement,
        faultAnalysis: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.faultAnalysis))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    detectedInPhoto: boolean;
    signType: string;
    timestamp: bigint;
    position: [] | [string];
}): {
    detectedInPhoto: boolean;
    signType: string;
    timestamp: bigint;
    position?: string;
} {
    return {
        detectedInPhoto: value.detectedInPhoto,
        signType: value.signType,
        timestamp: value.timestamp,
        position: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.position))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weatherConditions: [] | [string];
    speedLimit: [] | [bigint];
    isAtFault: boolean;
    violatedRules: Array<_HighwayCodeRule>;
    actualSpeed: [] | [bigint];
    reason: string;
}): {
    weatherConditions?: string;
    speedLimit?: bigint;
    isAtFault: boolean;
    violatedRules: Array<HighwayCodeRule>;
    actualSpeed?: bigint;
    reason: string;
} {
    return {
        weatherConditions: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.weatherConditions)),
        speedLimit: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.speedLimit)),
        isAtFault: value.isAtFault,
        violatedRules: value.violatedRules,
        actualSpeed: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.actualSpeed)),
        reason: value.reason
    };
}
async function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    blob: _ExternalBlob;
    bodyRegion: string;
    timestamp: bigint;
    reportId: bigint;
    crashType: string;
}): Promise<{
    id: bigint;
    blob: ExternalBlob;
    bodyRegion: string;
    timestamp: bigint;
    reportId: bigint;
    crashType: string;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n35(_uploadFile, _downloadFile, value.blob),
        bodyRegion: value.bodyRegion,
        timestamp: value.timestamp,
        reportId: value.reportId,
        crashType: value.crashType
    };
}
async function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    summary: string;
    injuryPhotos: Array<_InjuryPhoto>;
    reportId: bigint;
}): Promise<{
    owner: Principal;
    summary: string;
    injuryPhotos: Array<InjuryPhoto>;
    reportId: bigint;
}> {
    return {
        owner: value.owner,
        summary: value.summary,
        injuryPhotos: await from_candid_vec_n43(_uploadFile, _downloadFile, value.injuryPhotos),
        reportId: value.reportId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _AccidentReport]): Promise<[bigint, AccidentReport]> {
    return [
        value[0],
        await from_candid_AccidentReport_n25(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _AccidentReport]>): Promise<Array<[bigint, AccidentReport]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n24(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrafficSign>): Array<TrafficSign> {
    return value.map((x)=>from_candid_TrafficSign_n31(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n35(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InjuryPhoto>): Promise<Array<InjuryPhoto>> {
    return await Promise.all(value.map(async (x)=>await from_candid_InjuryPhoto_n44(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_RoadType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoadType): _RoadType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_TrafficSign_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrafficSign): _TrafficSign {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrafficSignalState | null): [] | [_TrafficSignalState] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OtherVehicle | null): [] | [_OtherVehicle] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    detectedInPhoto: boolean;
    signType: string;
    timestamp: bigint;
    position?: string;
}): {
    detectedInPhoto: boolean;
    signType: string;
    timestamp: bigint;
    position: [] | [string];
} {
    return {
        detectedInPhoto: value.detectedInPhoto,
        signType: value.signType,
        timestamp: value.timestamp,
        position: value.position ? candid_some(value.position) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [ExternalBlob, string, string]): Promise<[_ExternalBlob, string, string]> {
    return [
        await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value[0]),
        value[1],
        value[2]
    ];
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "urban";
    urban: bigint;
} | {
    __kind__: "dualCarriageway";
    dualCarriageway: bigint;
} | {
    __kind__: "motorway";
    motorway: bigint;
}): {
    urban: bigint;
} | {
    dualCarriageway: bigint;
} | {
    motorway: bigint;
} {
    return value.__kind__ === "urban" ? {
        urban: value.urban
    } : value.__kind__ === "dualCarriageway" ? {
        dualCarriageway: value.dualCarriageway
    } : value.__kind__ === "motorway" ? {
        motorway: value.motorway
    } : value;
}
function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TrafficSign>): Array<_TrafficSign> {
    return value.map((x)=>to_candid_TrafficSign_n17(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[ExternalBlob, string, string]>): Promise<Array<[_ExternalBlob, string, string]>> {
    return await Promise.all(value.map(async (x)=>await to_candid_tuple_n9(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
