/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoadType = IDL.Variant({
  'urban' : IDL.Nat,
  'dualCarriageway' : IDL.Nat,
  'motorway' : IDL.Nat,
});
export const PhotoMetadata = IDL.Record({
  'contentType' : IDL.Text,
  'description' : IDL.Text,
  'uploadTimestamp' : IDL.Int,
  'filename' : IDL.Text,
});
export const TrafficSignalState = IDL.Record({
  'color' : IDL.Text,
  'proximityToAccident' : IDL.Nat,
  'witnessTestimony' : IDL.Text,
  'position' : IDL.Text,
});
export const TrafficSign = IDL.Record({
  'detectedInPhoto' : IDL.Bool,
  'signType' : IDL.Text,
  'timestamp' : IDL.Int,
  'position' : IDL.Opt(IDL.Text),
});
export const Surroundings = IDL.Record({
  'roadCondition' : IDL.Text,
  'visibility' : IDL.Text,
  'weather' : IDL.Text,
});
export const VehicleInfo = IDL.Record({
  'mot' : IDL.Text,
  'model' : IDL.Text,
  'registration' : IDL.Text,
  'make' : IDL.Text,
  'year' : IDL.Nat,
  'licencePlate' : IDL.Text,
  'colour' : IDL.Text,
});
export const OtherVehicle = IDL.Record({
  'mot' : IDL.Text,
  'model' : IDL.Text,
  'ownerName' : IDL.Text,
  'registration' : IDL.Text,
  'make' : IDL.Text,
  'year' : IDL.Nat,
  'insurancePolicyNumber' : IDL.Text,
  'claimReference' : IDL.Text,
  'email' : IDL.Text,
  'insurer' : IDL.Text,
  'licencePlate' : IDL.Text,
  'phone' : IDL.Text,
  'colour' : IDL.Text,
});
export const Witness = IDL.Record({
  'statement' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const AIAnalysisResult = IDL.Record({
  'inferredCrashType' : IDL.Text,
  'narrativeText' : IDL.Text,
  'correlationSummary' : IDL.Text,
  'severity' : IDL.Text,
});
export const Violation = IDL.Record({
  'detectedAt' : IDL.Int,
  'description' : IDL.Text,
  'violationType' : IDL.Text,
});
export const HighwayCodeRule = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'ruleNumber' : IDL.Text,
  'applicableScenarios' : IDL.Vec(IDL.Text),
});
export const FaultAnalysis = IDL.Record({
  'weatherConditions' : IDL.Opt(IDL.Text),
  'speedLimit' : IDL.Opt(IDL.Nat),
  'isAtFault' : IDL.Bool,
  'violatedRules' : IDL.Vec(HighwayCodeRule),
  'actualSpeed' : IDL.Opt(IDL.Nat),
  'reason' : IDL.Text,
});
export const AccidentReport = IDL.Record({
  'party2Liability' : IDL.Opt(IDL.Nat),
  'vehicleInfo' : VehicleInfo,
  'isRedLightViolation' : IDL.Bool,
  'damageDescription' : IDL.Text,
  'imageData' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  'trafficSignalState' : IDL.Opt(TrafficSignalState),
  'otherVehicle' : IDL.Opt(OtherVehicle),
  'owner' : IDL.Opt(IDL.Principal),
  'party1Liability' : IDL.Opt(IDL.Nat),
  'aiAnalysisResult' : IDL.Opt(AIAnalysisResult),
  'stopLocation' : IDL.Text,
  'violations' : IDL.Vec(Violation),
  'applicableRules' : IDL.Vec(HighwayCodeRule),
  'trafficSigns' : IDL.Vec(TrafficSign),
  'faultReasoning' : IDL.Text,
  'surroundings' : Surroundings,
  'timestamp' : IDL.Int,
  'isAtFault' : IDL.Bool,
  'accidentMarker' : IDL.Text,
  'witnesses' : IDL.Vec(Witness),
  'videos' : IDL.Vec(ExternalBlob),
  'vehicleSpeed' : IDL.Nat,
  'photos' : IDL.Vec(PhotoMetadata),
  'witnessStatement' : IDL.Text,
  'faultAnalysis' : IDL.Opt(FaultAnalysis),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const InjuryPhoto = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'bodyRegion' : IDL.Text,
  'timestamp' : IDL.Int,
  'reportId' : IDL.Nat,
  'crashType' : IDL.Text,
});
export const InsuranceExport = IDL.Record({
  'owner' : IDL.Principal,
  'summary' : IDL.Text,
  'injuryPhotos' : IDL.Vec(InjuryPhoto),
  'reportId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInjuryPhotos' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(ExternalBlob, IDL.Text, IDL.Text))],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReport' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        RoadType,
        IDL.Vec(PhotoMetadata),
        IDL.Vec(IDL.Vec(IDL.Nat8)),
        IDL.Opt(TrafficSignalState),
        IDL.Vec(TrafficSign),
        IDL.Text,
        Surroundings,
        VehicleInfo,
        IDL.Opt(OtherVehicle),
        IDL.Vec(Witness),
        IDL.Vec(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteInjuryPhotos' : IDL.Func([IDL.Nat], [], []),
  'getAIAnalysisResult' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(AIAnalysisResult)],
      ['query'],
    ),
  'getAllPhotos' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(PhotoMetadata))],
      ['query'],
    ),
  'getAllReports' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, AccidentReport))],
      ['query'],
    ),
  'getAllThumbnails' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(PhotoMetadata)))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFirstPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(PhotoMetadata)], ['query']),
  'getInjuryPhotos' : IDL.Func([IDL.Nat], [IDL.Vec(InjuryPhoto)], ['query']),
  'getInsuranceExport' : IDL.Func([IDL.Nat], [InsuranceExport], ['query']),
  'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(AccidentReport)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'storeAIAnalysisResult' : IDL.Func([IDL.Nat, AIAnalysisResult], [], []),
  'storeInjuryPhotos' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'uploadPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [PhotoMetadata], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoadType = IDL.Variant({
    'urban' : IDL.Nat,
    'dualCarriageway' : IDL.Nat,
    'motorway' : IDL.Nat,
  });
  const PhotoMetadata = IDL.Record({
    'contentType' : IDL.Text,
    'description' : IDL.Text,
    'uploadTimestamp' : IDL.Int,
    'filename' : IDL.Text,
  });
  const TrafficSignalState = IDL.Record({
    'color' : IDL.Text,
    'proximityToAccident' : IDL.Nat,
    'witnessTestimony' : IDL.Text,
    'position' : IDL.Text,
  });
  const TrafficSign = IDL.Record({
    'detectedInPhoto' : IDL.Bool,
    'signType' : IDL.Text,
    'timestamp' : IDL.Int,
    'position' : IDL.Opt(IDL.Text),
  });
  const Surroundings = IDL.Record({
    'roadCondition' : IDL.Text,
    'visibility' : IDL.Text,
    'weather' : IDL.Text,
  });
  const VehicleInfo = IDL.Record({
    'mot' : IDL.Text,
    'model' : IDL.Text,
    'registration' : IDL.Text,
    'make' : IDL.Text,
    'year' : IDL.Nat,
    'licencePlate' : IDL.Text,
    'colour' : IDL.Text,
  });
  const OtherVehicle = IDL.Record({
    'mot' : IDL.Text,
    'model' : IDL.Text,
    'ownerName' : IDL.Text,
    'registration' : IDL.Text,
    'make' : IDL.Text,
    'year' : IDL.Nat,
    'insurancePolicyNumber' : IDL.Text,
    'claimReference' : IDL.Text,
    'email' : IDL.Text,
    'insurer' : IDL.Text,
    'licencePlate' : IDL.Text,
    'phone' : IDL.Text,
    'colour' : IDL.Text,
  });
  const Witness = IDL.Record({
    'statement' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AIAnalysisResult = IDL.Record({
    'inferredCrashType' : IDL.Text,
    'narrativeText' : IDL.Text,
    'correlationSummary' : IDL.Text,
    'severity' : IDL.Text,
  });
  const Violation = IDL.Record({
    'detectedAt' : IDL.Int,
    'description' : IDL.Text,
    'violationType' : IDL.Text,
  });
  const HighwayCodeRule = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'ruleNumber' : IDL.Text,
    'applicableScenarios' : IDL.Vec(IDL.Text),
  });
  const FaultAnalysis = IDL.Record({
    'weatherConditions' : IDL.Opt(IDL.Text),
    'speedLimit' : IDL.Opt(IDL.Nat),
    'isAtFault' : IDL.Bool,
    'violatedRules' : IDL.Vec(HighwayCodeRule),
    'actualSpeed' : IDL.Opt(IDL.Nat),
    'reason' : IDL.Text,
  });
  const AccidentReport = IDL.Record({
    'party2Liability' : IDL.Opt(IDL.Nat),
    'vehicleInfo' : VehicleInfo,
    'isRedLightViolation' : IDL.Bool,
    'damageDescription' : IDL.Text,
    'imageData' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'trafficSignalState' : IDL.Opt(TrafficSignalState),
    'otherVehicle' : IDL.Opt(OtherVehicle),
    'owner' : IDL.Opt(IDL.Principal),
    'party1Liability' : IDL.Opt(IDL.Nat),
    'aiAnalysisResult' : IDL.Opt(AIAnalysisResult),
    'stopLocation' : IDL.Text,
    'violations' : IDL.Vec(Violation),
    'applicableRules' : IDL.Vec(HighwayCodeRule),
    'trafficSigns' : IDL.Vec(TrafficSign),
    'faultReasoning' : IDL.Text,
    'surroundings' : Surroundings,
    'timestamp' : IDL.Int,
    'isAtFault' : IDL.Bool,
    'accidentMarker' : IDL.Text,
    'witnesses' : IDL.Vec(Witness),
    'videos' : IDL.Vec(ExternalBlob),
    'vehicleSpeed' : IDL.Nat,
    'photos' : IDL.Vec(PhotoMetadata),
    'witnessStatement' : IDL.Text,
    'faultAnalysis' : IDL.Opt(FaultAnalysis),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const InjuryPhoto = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'bodyRegion' : IDL.Text,
    'timestamp' : IDL.Int,
    'reportId' : IDL.Nat,
    'crashType' : IDL.Text,
  });
  const InsuranceExport = IDL.Record({
    'owner' : IDL.Principal,
    'summary' : IDL.Text,
    'injuryPhotos' : IDL.Vec(InjuryPhoto),
    'reportId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInjuryPhotos' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(ExternalBlob, IDL.Text, IDL.Text))],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReport' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          RoadType,
          IDL.Vec(PhotoMetadata),
          IDL.Vec(IDL.Vec(IDL.Nat8)),
          IDL.Opt(TrafficSignalState),
          IDL.Vec(TrafficSign),
          IDL.Text,
          Surroundings,
          VehicleInfo,
          IDL.Opt(OtherVehicle),
          IDL.Vec(Witness),
          IDL.Vec(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteInjuryPhotos' : IDL.Func([IDL.Nat], [], []),
    'getAIAnalysisResult' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AIAnalysisResult)],
        ['query'],
      ),
    'getAllPhotos' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(PhotoMetadata))],
        ['query'],
      ),
    'getAllReports' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, AccidentReport))],
        ['query'],
      ),
    'getAllThumbnails' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(PhotoMetadata)))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFirstPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(PhotoMetadata)], ['query']),
    'getInjuryPhotos' : IDL.Func([IDL.Nat], [IDL.Vec(InjuryPhoto)], ['query']),
    'getInsuranceExport' : IDL.Func([IDL.Nat], [InsuranceExport], ['query']),
    'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(AccidentReport)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'storeAIAnalysisResult' : IDL.Func([IDL.Nat, AIAnalysisResult], [], []),
    'storeInjuryPhotos' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'uploadPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [PhotoMetadata],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };